import { Inter } from 'next/font/google'
import './globals.css'
import NavTop from '@/components/NavTop'
import MiContexto from '@/context/contextApp'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'UrbanNav',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

<html lang="en">
      <head>
      <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
  integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
  crossOrigin="anonymous"
/>
    <link rel="stylesheet" href="../styles/global.css" />
      </head>
      <body className={inter.className}>
        <Providers>
        <NavTop />
          <div className="mt-5">
          {children}
          </div>
        </Providers>
        </body>
    </html>

  )
}
